package stp.repository.quartz.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import stp.repository.quartz.model.ScheduleJob;
import stp.repository.quartz.model.ScheduleJobExample;

public interface ScheduleJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    int countByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    int deleteByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    int insert(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    int insertSelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    List<ScheduleJob> selectByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    ScheduleJob selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") ScheduleJob record, @Param("example") ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    int updateByExample(@Param("record") ScheduleJob record, @Param("example") ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    int updateByPrimaryKeySelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEDULE_JOB
     *
     * @mbggenerated Mon Aug 10 15:52:45 CST 2015
     */
    int updateByPrimaryKey(ScheduleJob record);
}